// <auto-generated />
namespace EmployeeEvaluation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactoringsurveytemplate01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoringsurveytemplate01));
        
        string IMigrationMetadata.Id
        {
            get { return "201809042001574_refactoring survey template 01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
