// <auto-generated />
namespace EmployeeEvaluation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactoringsurveytemplate04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoringsurveytemplate04));
        
        string IMigrationMetadata.Id
        {
            get { return "201809042047212_refactoring survey template 04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
